---
- name: Delete | import common tasks
  tags:
    - keystone
    - openstack
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | remove packages
  tags:
    - keystone
    - openstack
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ packages }}"
  become: true

- name: DB | delete database
  tags:
    - keystone
    - openstack
  community.mysql.mysql_db:
    login_unix_socket: "{{ mariadb_service_socket }}"
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ os_service_name }}"
    state: absent
  delegate_to: "{{ groups['mariadb'][0] }}"
  run_once: true
  no_log: true

- name: Delete | delete config directory
  tags:
    - keystone
    - openstack
  ansible.builtin.file:
    path: "{{ os_conf_dir }}"
    state: absent
  become: true

- name: Delete | delete adminrc and cluster.yml
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.HOME }}/.config/openstack"
    - "{{ ansible_env.HOME }}/.adminrc"

- name: Delete | remove adminrc in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regex: "^source.*adminrc"
    state: absent
...
